version: '3.7'
services:
  mautic:
    image: garagist/mautic:composer-8.0
    container_name: mautic
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 80:80
      - 443:443
    environment:
      - MAUTIC_CONTEXT=Production
      - MAUTIC_SSL_ENABLED=true
      - MAUTIC_TLS_EMAIL=ops@neos.io
    volumes:
      - .mautic/config:/config
      - .mautic/composer.json:/data/composer.json

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mautic4
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=password
    volumes:
      - .mautic/mysql/data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""
