version: '3.7'
services:
  mautic:
    image: garagist/mautic:4.4.3
    ports:
      - 8090:80
    environment:
      - MAUTIC_CONTEXT=Production
    volumes:
      - .mautic/config:/config
      - .mautic/composer.json:/data/composer.json

  database:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      - MYSQL_DATABASE=mautic4
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=password
    volumes:
      - .mautic/mysql/data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""
